# Generated by Django 5.0.4 on 2024-04-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/gallerie/')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('description', models.TimeField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(max_length=75)),
                ('hidden', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='galleries.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='galleries.image'),
        ),
    ]
