# Generated by Django 5.0.4 on 2024-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='capture_date',
            field=models.DateTimeField(null=True, verbose_name='Date picture was take'),
        ),
        migrations.AddField(
            model_name='image',
            name='photographer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
