# Generated by Django 5.0.4 on 2024-04-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_alter_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='galleries.image'),
        ),
    ]
